[project]
dynamic = ["classifiers", "version", "readme", "authors", "requires-python", "description"]
dependencies = [
    "pyautogen>=0.2.19",
    "composio_core===0.2.16"
]
name = "composio_autogen"

[build-system]
requires = [ "setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
