# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

#Currently set to run every Friday at 06:30 UTC/12:00 IST
version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "friday"
      time: "6:30"
