[project]
name = "composio-openai-agents"
version = "0.8.6"
description = "Use Composio to get array of strongly typed tools for OpenAI Agents"
readme = "README.md"
requires-python = ">=3.9,<4"
authors = [
    { name = "Composio", email = "tech@composio.dev" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "openai-agents>=0.0.3",
    "composio",
]

[project.urls]
Homepage = "https://github.com/ComposioHQ/composio"
