paths:
  /api/v3/mcp/validate/{uuid}:
    get:
      x-fern-ignore: true
  /api/v3/cli/get-session:
    get:
      x-fern-ignore: true
  /api/v3/cli/create-session:
    post:
      x-fern-ignore: true
  /api/v3/auth/session/logout:
    post:
      x-fern-ignore: true
  /api/v3/tool_router/session/{session_id}/execute:
    post:
      parameters:
        - name: x-session-access-key
          x-fern-ignore: true
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: API key authentication
    CookieAuth:
      # type: apiKey
      # in: header
      # name: authToken
      # description: Cookie based authentication
